### PR TITLE
Pages

### PR DESCRIPTION
**Pull request by mimansha-swarup**
email: [adarshbalika@gmail.com](mailto:adarshbalika@gmail.com)
password: adarshBalika123
- single page for videos
- watch later
- history

https://user-images.githubusercontent.com/69811810/161726095-d931483a-3a2e-4356-b9a2-5e1d614ccabc.mp4

### CODE REVIEW

**Comment by percius47** [comment]
my signup is failing so couldnt review the features comprehensively. Design looks good with the theme. good job!

**Comment by mimansha-swarup** [comment]
> my signup is failing so couldnt review the features comprehensively. Design looks good with the theme. good job!

use login credentials 
email: [adarshbalika@gmail.com](mailto:adarshbalika@gmail.com)
password: adarshBalika123

I will look into it

**Review by percius47 — APPROVED** [review]
looks cool, nice touch on the options in single video player page. Great work.

**Review by manojasarsa — APPROVED** [review]
The code seems to be well structured and clean.
good to merge!

**Pull request merged**
